[package]
name = "pulsar-lite-storage-managed-ledger-rocksdb"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pulsar-lite-metrics = { path = "../../metrics" }
pulsar-lite-proto = { path = "../../proto" }
pulsar-lite-storage-managed-ledger = { path = "../managed-ledger" }
anyhow.workspace = true
rocksdb = "0.24"
prost = "0.13"
serde.workspace = true
bincode = "3.0"
log.workspace = true
tokio = { workspace = true }
arc-swap = "1.7"

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
tempfile = "3.9"
tokio = { version = "1", features = ["macros", "rt"] }
bincode = "3.0"
prost = "0.13"
