FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY rust/target/release/pulsar-lite /app/pulsar-lite
COPY rust/pulsar-lite.toml /app/pulsar-lite.toml

EXPOSE 6651 6652

CMD ["/app/pulsar-lite"]
